# Site settings
alert-message: ' and <a href="http://getbootstrap.com" class="alert-link">http://getbootstrap.com</a>.'
category-list: [Widgets, Charts, Layouts, Alternate Layouts]
company: PatternFly
navbar-pf-navbar-brand-icon: true
navbar-pf-alt-navbar-brand-icon: true
navbar-brand-icon: '../dist/img/logo-alt.svg'
navbar-alt-brand-icon: '../dist/img/brand-alt.svg'
title: PatternFly
title-product: 'PatternFly Enterprise Application'
url-css-additions: '../dist/css/patternfly-additions.min.css'
url-css-extra: 'tests.css'
url-css-main: '../dist/css/patternfly.min.css'
url-img: 'img/'
url-js: '../dist/js/patternfly.min.js'
